### ISSUE TITLE
Ord...

### ISSUE THREAD

**Issue by Ulvtand** [xdy/foundryvtt-lang-sv#7]
Tydligen så känner inte Foundry till ett ord:

<img width="494" alt="image" src="https://github.com/user-attachments/assets/3d064392-aaac-4d1a-81ba-a34aeb86d874">

<img width="515" alt="image" src="https://github.com/user-attachments/assets/70004317-8c97-4a1d-a110-fa556c425c7d">

Vilket gör att modulen stannar upp.

**Comment by xdy** [comment]
Se där! Den trodde jag att jag hade städat bort för länge sen. Dessutom hade jag fetfingrat in skräptecken i sv.json, men, med version 4.0.3 Funkar Det På Min Maskin(tm) :)
